spring:
  application:
    name: auth-app
  datasource:
    url: jdbc:mysql://localhost:3306/auth-app?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: auth-app-pool
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 3000
      idle-timeout: 600000
      max-lifetime: 1740000
      validation-timeout: 1000
      leak-detection-threshold: 20000
      initialization-fail-timeout: 1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true

server:
  port: 8082

logging:
  level:
    org.springframework.security: DEBUG

security:
  jwt:
    secret: ${JWT_SECRET:258b67b9da8be40b7af5960068fdf0e4faa81738bf56615e146574f9e117cc73a86ce0803718b114c2a811a24065484345855013354b31723a4f947f27baf1aa}
    issuer: ${JWT_ISSUER:api.substring.com}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}


# Email and SMS configs

# Oauth Configs

